### ISSUE TITLE
elasticsearch connect error

### ISSUE THREAD

**Issue by imperio-wxm** [albertocsm/presto#33]
**I build project and install es plugin,however I got this error in server.log:**

```java
2017-12-12T14:53:10.002+0800    ERROR   main    com.facebook.presto.server.PrestoServer Method com/facebook/presto/elasticsearch/ElasticsearchPlugin.getServices(Ljava/lang/Class;)Ljava/util/List; is abstract
java.lang.AbstractMethodError: Method com/facebook/presto/elasticsearch/ElasticsearchPlugin.getServices(Ljava/lang/Class;)Ljava/util/List; is abstract
        at com.facebook.presto.elasticsearch.ElasticsearchPlugin.getServices(ElasticsearchPlugin.java)
        at com.facebook.presto.server.PluginManager.installPlugin(PluginManager.java:194)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:184)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:167)
        at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:148)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:113)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:63)
```

**Comment by albertocsm** [comment]
Have you created the config file for the plug-in?

On Dec 12, 2017 6:57 AM, "wxmimperio" <notifications@github.com> wrote:

*I build project and install es plugin,however I got this error in
server.log:*

2017-12-12T14:53:10.002+0800    ERROR   main
com.facebook.presto.server.PrestoServer Method
com/facebook/presto/elasticsearch/ElasticsearchPlugin.getServices(Ljava/lang/Class;)Ljava/util/List;
is abstractjava.lang.AbstractMethodError: Method
com/facebook/presto/elasticsearch/ElasticsearchPlugin.getServices(Ljava/lang/Class;)Ljava/util/List;
is abstract
        at com.facebook.presto.elasticsearch.ElasticsearchPlugin.getServices(ElasticsearchPlugin.java)
        at com.facebook.presto.server.PluginManager.installPlugin(PluginManager.java:194)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:184)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:167)
        at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:148)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:113)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:63)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/albertocsm/presto/issues/33>, or mute the thread

**Comment by imperio-wxm** [comment]
@albertocsm 

Yes. My config named es.properties and like this:
```java
connector.name=elasticsearch
elasticsearch-server=localhost
elasticsearch-port=9300
elasticsearch-clustername=elasticsearch_demo
```

**Comment by albertocsm** [comment]
you are missing the ES plugin specific configuration file
check https://github.com/albertocsm/presto/issues/30

**Comment by imperio-wxm** [comment]
@albertocsm 
so, what is the meaning of file: ///myPath/myschemafile.json?
All table schemas should be listed in schems.json?

If I just have on es cluster and I want to select all tables,what should I set this config?
