### ISSUE TITLE
fix class loader issue with Elasticsearch's "names.txt" not being found

### ISSUE THREAD

**Issue by albertocsm** [albertocsm/presto#9]
its a TCCL problem...

**Comment by mateilucianstefan** [comment]
org.elasticsearch.env.FailedToResolveConfigException: Failed to resolve config path [names.txt], tried file path [names.txt], path file [~workspace/presto-main/config/names.txt], and classpath
    at org.elasticsearch.env.Environment.resolveConfig(Environment.java:242)
    at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:140)
    at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:60)
    at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:159)
    at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:125)
    at com.facebook.presto.elasticsearch.ElasticsearchClient.getMappings(ElasticsearchClient.java:156)
    at com.facebook.presto.elasticsearch.ElasticsearchClient.getColumns(ElasticsearchClient.java:178)
    at com.facebook.presto.elasticsearch.ElasticsearchClient.updateTableColumns(ElasticsearchClient.java:277)
    at com.facebook.presto.elasticsearch.ElasticsearchClient.updateSchemas(ElasticsearchClient.java:128)
    at com.facebook.presto.elasticsearch.ElasticsearchClient.getTable(ElasticsearchClient.java:104)
    at com.facebook.presto.elasticsearch.ElasticsearchMetadata.getTableHandle(ElasticsearchMetadata.java:77)
    at com.facebook.presto.elasticsearch.ElasticsearchMetadata.getTableHandle(ElasticsearchMetadata.java:45)
    at com.facebook.presto.metadata.MetadataManager.getTableHandle(MetadataManager.java:281)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitShowColumns(StatementAnalyzer.java:317) [...]

**Comment by albertocsm** [comment]
the workaround is copying elasticsearch's names.txt to /var/presto/data/config
